"""
Every directory this project reads or writes, defined once.

Before this module existed, HERE / OUT / OUT_DIR / FIG_DIR / LOG_DIR / VENDOR
were recomputed in nine separate files, twice under two different names for the
same folder. A path that is spelled once cannot drift.

Output directories are created on import, so no caller needs os.makedirs.

Author: Badhon Kumar
"""

from pathlib import Path

# continuum_sim/paths.py -> continuum_sim/ -> MuJoCo_Sim/
ROOT = Path(__file__).resolve().parent.parent

PACKAGE   = ROOT / "continuum_sim"
CHECKS    = ROOT / "checks"
TOOLS     = ROOT / "tools"

CONTROLLER = ROOT / "controller"            # vendored, byte-identical - never edit
MANIFEST   = CONTROLLER / "MANIFEST.sha256"
MODELS     = ROOT / "models"
MJCF       = MODELS / "continuum_planar.xml"    # GENERATED by build_model.py
GCODE      = ROOT / "gcode"
ASSETS     = ROOT / "assets"

OUTPUTS = ROOT / "outputs"
FIGURES = OUTPUTS / "figures"
LOGS    = OUTPUTS / "logs"
VIDEO   = OUTPUTS / "video"

# The sibling folder the vendored controller came from. Optional: MuJoCo_Sim is
# self-contained, and its absence is a normal standalone install, not an error.
UPSTREAM = ROOT.parent / "Continuum_v3"

for _d in (ASSETS, OUTPUTS, FIGURES, LOGS, VIDEO):
    _d.mkdir(parents=True, exist_ok=True)
