"""
Generates the planar continuum-manipulator MJCF from the parameters in sim/params.py.

Phase 1 scope: geometry and elastic backbone only. No tendons, no actuators -
those arrive in Phase 2.

Model layout (planar, motion confined to the world x-y plane):

    base disk (welded to world, at origin)
      link 1  .. link 6    segment 1   } each link = one 15 mm axial disk pitch,
      link 7  .. link 12   segment 2   } carrying a spacer disk at its distal
      link 13 .. link 18   segment 3   } face, or an end disk if last in segment
        site "tip" at the distal face of link 18

Every joint is a hinge about +z, so the arm can only bend in the x-y plane.
Undeformed, the arm lies along +x with its tip at (0.270, 0, 0).

Run standalone to (re)generate models/continuum_planar.xml:
    python MuJoCo_Sim/models/build_model.py

Author: Badhon Kumar
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sim import params as P

XML_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "continuum_planar.xml")


def build_xml(links_per_seg: int = None,
              stiffness: float = None,
              damping: float = None,
              armature: float = None,
              gravity=None,
              timestep: float = None,
              contacts: bool = None,
              tendons: bool = True,
              seg_stiffness_scale=None,
              tendon_kp: float = None) -> str:
    """
    Build the MJCF as a string.

    links_per_seg is exposed so the discretization-sensitivity study can vary it.
    When it changes, joint stiffness is rescaled by k = EI/ds: halving the link
    length doubles the number of springs, so each must be twice as stiff to
    represent the same physical rod. Without this rescaling a sensitivity sweep
    would measure the stiffness change, not the discretization.
    """
    n_per_seg = links_per_seg if links_per_seg is not None else P.LINKS_PER_SEG
    damping = P.JOINT_DAMPING if damping is None else damping
    armature = P.JOINT_ARMATURE if armature is None else armature
    gravity = P.GRAVITY if gravity is None else gravity
    timestep = P.TIMESTEP if timestep is None else timestep
    contacts = P.ENABLE_CONTACTS if contacts is None else contacts
    tendon_kp = P.TENDON_KP if tendon_kp is None else tendon_kp

    if stiffness is None:
        stiffness = P.JOINT_STIFFNESS * (n_per_seg / P.LINKS_PER_SEG)

    # Per-segment stiffness multipliers. Phase 3 fits these: the three segments
    # share one backbone but have different tendon moment arms, so a single
    # global stiffness need not reproduce all three segments equally well.
    if seg_stiffness_scale is None:
        seg_stiffness_scale = [1.0] * P.N_SEG

    n_links = P.N_SEG * n_per_seg
    link_len = P.L_SEG[0] / n_per_seg
    con = "1" if contacts else "0"
    grav = " ".join(f"{g:g}" for g in gravity)

    # Last link index (0-based) each motor's tendon reaches before terminating.
    term_link = [(P.MOTOR_TO_SEG[k] + 1) * n_per_seg - 1 for k in range(P.N_MOTORS)]

    head = f"""<mujoco model="continuum_planar">
  <!-- GENERATED by models/build_model.py - edit params.py, not this file. -->

  <compiler angle="radian" autolimits="true"/>

  <option timestep="{timestep}" gravity="{grav}" integrator="implicitfast">
    <flag energy="enable"/>
  </option>

  <default>
    <joint type="hinge" axis="0 0 1"
           stiffness="{stiffness:.6g}" damping="{damping:.6g}" armature="{armature:.6g}"/>
    <geom contype="{con}" conaffinity="{con}"/>
  </default>

  <visual>
    <headlight ambient="0.45 0.45 0.45" diffuse="0.6 0.6 0.6"/>
    <rgba haze="0.9 0.92 0.95 1"/>
    <global offwidth="1920" offheight="1080"/>
  </visual>

  <worldbody>
    <light pos="0.15 0 0.6" dir="0 0 -1" diffuse="0.7 0.7 0.7"/>

    <!-- Looks straight down -z onto the x-y bending plane. -->
    <camera name="planar" pos="{P.TOTAL_LEN/2:.4f} 0 0.45" xyaxes="1 0 0 0 1 0"/>

    <!-- Base disk, welded to the world: no joint between it and worldbody. -->
    <body name="base" pos="0 0 0">
      <geom name="base_disk" type="cylinder"
            fromto="{-P.BASE_DISK_THICK:.6f} 0 0 0 0 0"
            size="{P.BASE_DISK_RADIUS:.6f}" rgba="{P.BASE_COLOR}"
            density="{P.DISK_DENSITY:g}"/>
      <site name="origin" pos="0 0 0" size="0.002" rgba="0.5 0.5 0.5 1"/>
"""

    # Tendon routing sites on the base disk. The base disk is where every tendon
    # is at its most inboard radius, since it is furthest from its own segment.
    tendon_sites = {k: [] for k in range(P.N_MOTORS)}
    if tendons:
        for k in range(P.N_MOTORS):
            r = P.tendon_radius(k, 0)
            head += (f'      <site name="m{k+1}_s0" pos="0 {r:.6f} 0" '
                     f'size="0.0008" rgba="0.8 0.2 0.2 0.6"/>\n')
            tendon_sites[k].append(f"m{k+1}_s0")

    # Hinges sit at the CENTRE of each link, so the chain begins and ends with a
    # half-link. This makes the tip sum a trapezoidal rule over the arc and gives
    # second-order accuracy. Placing hinges at the proximal end instead leaves the
    # first link already rotated while the true arc tangent is still 0; that
    # half-angle bias accumulates and cost 15 mm of tip error at 60 deg/segment.
    hl = link_len / 2.0

    body = ""
    for i in range(n_links):
        seg = min(i // n_per_seg, P.N_SEG - 1)
        last_in_seg = (i % n_per_seg) == (n_per_seg - 1)
        indent = "      " + "  " * (i + 1)
        pos = f"{hl:.6f} 0 0" if i == 0 else f"{link_len:.6f} 0 0"

        # End disks mark segment boundaries: slightly thicker and tinted with the
        # segment colour, so Phase 2 tendon terminations are visually unambiguous.
        disk_thick = P.DISK_THICK * (2.0 if last_in_seg else 1.0)
        disk_color = P.SEG_COLORS[seg] if last_in_seg else P.DISK_COLOR
        dh = disk_thick / 2.0

        k_joint = stiffness * seg_stiffness_scale[seg]
        body += f"""{indent}<body name="link{i+1}" pos="{pos}">
{indent}  <joint name="j{i+1}" stiffness="{k_joint:.6g}"/>
{indent}  <geom name="bb{i+1}" type="capsule"
{indent}        fromto="{-hl:.6f} 0 0 {hl:.6f} 0 0" size="{P.BACKBONE_RADIUS:.6f}"
{indent}        rgba="{P.SEG_COLORS[seg]}" density="{P.BACKBONE_DENSITY:g}"/>
{indent}  <geom name="disk{i+1}" type="cylinder"
{indent}        fromto="{hl-dh:.6f} 0 0 {hl+dh:.6f} 0 0"
{indent}        size="{P.DISK_RADIUS:.6f}" rgba="{disk_color}"
{indent}        density="{P.DISK_DENSITY:g}"/>
"""
        if last_in_seg:
            body += (f'{indent}  <site name="seg{seg+1}_end" '
                     f'pos="{hl:.6f} 0 0" size="0.0025" '
                     f'rgba="{P.SEG_COLORS[seg]}"/>\n')

        # Tendon routing holes at this link's disk. A motor's tendon threads
        # through every disk from the base to its own segment's end disk, and its
        # radius STEPS at each segment boundary (5 mm in its own segment, 3.5 mm
        # one segment back, 2 mm two back) - the paper's scheme for keeping the
        # three tendon pairs clear of each other.
        #
        # Consequence: bending a lower segment changes the path length of every
        # tendon passing through it, so the segments are genuinely coupled. The
        # controller models exactly this in pcc_angles(), which is why the radii
        # must follow the same scheme or plant and controller disagree by
        # construction.
        if tendons:
            for k in range(P.N_MOTORS):
                if i <= term_link[k]:
                    # Disk i+1 terminates the span belonging to segment `seg`.
                    r = P.tendon_radius(k, seg)
                    body += (f'{indent}  <site name="m{k+1}_s{i+1}" '
                             f'pos="{hl:.6f} {r:.6f} 0" size="0.0008" '
                             f'rgba="0.8 0.2 0.2 0.6"/>\n')
                    tendon_sites[k].append(f"m{k+1}_s{i+1}")

                    # At a segment boundary the tendon steps to its next radius.
                    # Placing that step at the SAME axial station (a second hole
                    # in the same disk) keeps every span at a constant radius, so
                    # the effective moment arms come out exact. Spreading the
                    # step across an axial span instead costs ~2.4% of the
                    # own-segment moment arm, which would show up later as
                    # fictitious model error.
                    if last_in_seg and P.MOTOR_TO_SEG[k] > seg:
                        r2 = P.tendon_radius(k, seg + 1)
                        body += (f'{indent}  <site name="m{k+1}_s{i+1}x" '
                                 f'pos="{hl:.6f} {r2:.6f} 0" size="0.0008" '
                                 f'rgba="0.8 0.2 0.2 0.6"/>\n')
                        tendon_sites[k].append(f"m{k+1}_s{i+1}x")

    # The tip site is the nozzle mount and the pose measurement point.
    tip_indent = "      " + "  " * (n_links + 1)
    body += (f'{tip_indent}<site name="tip" pos="{hl:.6f} 0 0" '
             f'size="0.003" rgba="{P.TIP_COLOR}"/>\n')

    for i in range(n_links, 0, -1):
        body += "      " + "  " * i + "</body>\n"

    tail = """    </body>
  </worldbody>
"""

    if tendons:
        tail += "\n  <tendon>\n"
        for k in range(P.N_MOTORS):
            seg = P.MOTOR_TO_SEG[k]
            tail += (f'    <spatial name="m{k+1}" width="{P.TENDON_WIDTH:.6f}" '
                     f'rgba="{P.SEG_COLORS[seg]}">\n')
            for name in tendon_sites[k]:
                tail += f'      <site site="{name}"/>\n'
            tail += "    </spatial>\n"
        tail += "  </tendon>\n"

        # ctrl is the commanded tendon LENGTH. forcerange is clamped to the
        # negative half so an actuator can only shorten its tendon: a released
        # tendon goes slack at zero force instead of unphysically pushing.
        tail += "\n  <actuator>\n"
        for k in range(P.N_MOTORS):
            # Generous ctrlrange around the nominal rest length; the exact rest
            # length is read back from the compiled model at runtime.
            rest = P.nominal_rest_length(k)
            lo = rest - P.TENDON_CTRL_MARGIN
            hi = rest + P.TENDON_CTRL_MARGIN
            tail += (f'    <position name="m{k+1}" tendon="m{k+1}" '
                     f'kp="{tendon_kp:.6g}" '
                     f'ctrlrange="{lo:.6f} {hi:.6f}" '
                     f'forcerange="{-P.TENDON_FORCE_MAX:.6g} 0"/>\n')
        tail += "  </actuator>\n"

    tail += "</mujoco>\n"
    return head + body + tail


def write_xml(path: str = XML_PATH, **kwargs) -> str:
    xml = build_xml(**kwargs)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(xml)
    return path


if __name__ == "__main__":
    p = write_xml()
    n = P.N_LINKS
    print(f"Wrote {p}")
    print(f"  {P.N_SEG} segments x {P.LINKS_PER_SEG} links = {n} links, "
          f"{P.LINK_LEN*1000:.1f} mm each, {P.TOTAL_LEN*1000:.0f} mm total")
